services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/certificate.crt:/etc/nginx/certs/certificate.crt:ro
      - ./certs/private.key:/etc/nginx/certs/private.key:ro